# Generated by Django 5.2.7 on 2026-06-01 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_member_address_member_age_member_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalrequest',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to='website.member'),
        ),
    ]
