# Generated by Django 5.2.7 on 2026-06-06 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_approvalrequest_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='faculty',
            field=models.CharField(blank=True, choices=[('CCSICT', 'CCSICT'), ('PS', 'PS'), ('CCJE', 'CCJE'), ('SAS', 'SAS'), ('CED', 'CED'), ('CBM', 'CBM'), ('IAT', 'IAT')], default='CCSICT', max_length=20),
        ),
    ]
