# Generated by Django 5.2.7 on 2026-06-20 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_add_geofence_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancelog',
            name='check_in_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
