# Generated by Django 5.2.7 on 2026-06-21 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_attendancelog_check_in_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendanceevent',
            name='checkin_time_in',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendanceevent',
            name='checkin_time_out',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
