# Generated by Django 5.2.7 on 2026-06-21 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_attendanceevent_checkin_time_in_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendanceevent',
            name='checkin_time_in_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendanceevent',
            name='checkin_time_out_end',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
