# Generated by Django 5.2.7 on 2026-06-21 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_attendanceevent_checkin_time_in_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancelog',
            name='check_out_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
