# Generated by Django 5.2.14 on 2026-07-06 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_system', '0027_backfill_medical_aid_validated_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id_PK', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'DEPARTMENT',
                'ordering': ['name'],
            },
        ),
        migrations.RenameIndex(
            model_name='sensitivereadlog',
            new_name='SENSITIVE_R_table_n_c95688_idx',
            old_name='sensitive_read_log_table_record_idx',
        ),
        migrations.RenameIndex(
            model_name='sensitivereadlog',
            new_name='SENSITIVE_R_read_at_121b97_idx',
            old_name='sensitive_read_log_read_at_idx',
        ),
        migrations.AddField(
            model_name='department',
            name='head_officer_id_FK',
            field=models.ForeignKey(blank=True, db_column='head_officer_id_FK', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_departments', to='core_system.officeruser'),
        ),
        migrations.AddField(
            model_name='member',
            name='department_id_FK',
            field=models.ForeignKey(blank=True, db_column='department_id_FK', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='core_system.department'),
        ),
    ]
