# Generated by Django 5.2.16 on 2026-07-24 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_system', '0063_add_contribution_recorded_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='officeruser',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
