# Generated by Django 5.2.16 on 2026-07-25 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_system', '0064_alter_member_email_alter_officeruser_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='officeruser',
            name='mfa_enabled',
        ),
        migrations.AddField(
            model_name='medicalaid',
            name='reason',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
