# Generated by Django 5.2.7 on 2026-07-31 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_system', '0093_newsarticle_newscategory_newsgallery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.deletion.SET_NULL, related_name='authored_news', to='core_system.officeruser'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.deletion.SET_NULL, related_name='articles', to='core_system.newscategory'),
        ),
        migrations.AddField(
            model_name='newsgallery',
            name='article',
            field=models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='galleries', to='core_system.newsarticle'),
        ),
    ]
