# Generated by Django 5.2.16 on 2026-08-09 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_system', '0103_monthlydues_is_advance'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryDeductionExemption',
            fields=[
                ('exemption_id_PK', models.AutoField(primary_key=True, serialize=False)),
                ('month_covered', models.CharField(max_length=50)),
                ('reason', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=50)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('requested_by_member', models.BooleanField(default=False)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_remarks', models.TextField(blank=True, null=True)),
                ('member_id_FK', models.ForeignKey(db_column='member_id_FK', on_delete=django.db.models.deletion.CASCADE, related_name='salary_deduction_exemptions', to='core_system.member')),
                ('reviewed_by_user_id_FK', models.ForeignKey(blank=True, db_column='reviewed_by_user_id_FK', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_system.officeruser')),
            ],
            options={
                'db_table': 'SALARY_DEDUCTION_EXEMPTION',
                'ordering': ['-requested_at'],
            },
        ),
    ]
