# Generated by Django 5.2.16 on 2026-08-09 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_system', '0104_salarydeductionexemption'),
    ]

    operations = [
        migrations.AddField(
            model_name='aidtrackingpost',
            name='finish_cycle',
            field=models.PositiveSmallIntegerField(default=1, help_text='1 = fund disbursement cycle, 2 = repayment close cycle (paid-with-funds only)'),
        ),
    ]
